FROM public.ecr.aws/lambda/nodejs:18

# Copy function code
COPY . ${LAMBDA_TASK_ROOT}
WORKDIR ${LAMBDA_TASK_ROOT}
RUN npm install

ENV NODE_ENV="test"
ENV TEST_MONGODB_URI=""
ENV MONGODB_URI=""
ENV PORT=3001
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda.handler" ]